### ISSUE TITLE
Extension and userscript stopped working

### ISSUE THREAD

**Issue by hschoen3** [tadwohlrapp/udemy-improved-course-library#10]
sometimes plugin is down and shows empty area instead of the reatings
![image](https://github.com/tadwohlrapp/udemy-improved-course-library/assets/141274038/1d707232-9e58-4597-aa78-167cacf34325)

**Comment by lundeen-bryan** [comment]
You're issue is correct but...

@hschoen3  you should edit the title of this bug report so that Tad knows what issue is being reported. 

I also noticed the issue and it is a repeat of a previous bug report I submitted here:
https://github.com/tadwohlrapp/udemy-improved-course-library/issues/8

So a good title would be "Bug Report | repeat of Issue #8 course time, create date and other text not showing"

Then he will have a clue about where to start looking for a solution.

**Comment by tadwohlrapp** [comment]
@hschoen3 

Thank you for bringing that to my attention! You're right, it's currently broken. I'll try to deploy a fix today or tomorrow.
